### PR TITLE
Use Path.Combine to combine paths

### PR DESCRIPTION
**Pull request by UrtsiSantsi**

### CODE REVIEW

**Comment by nlogozzo** [comment]
I don't see the benefit over using combine instead of how we do it currently...

**Comment by UrtsiSantsi** [comment]
The benefits are:
- It checks whether the first path already has a separator at the end so it will not duplicate the separators
- It checks both paths for invalid characters
- It better states the intent
- It is shorter :)

**Comment by nlogozzo** [comment]
> It checks both paths for invalid characters

This is the only reason why I'll accept the change. Didn't know `Path.Combine` did this...

**Review by nlogozzo — APPROVED** [review]

**Comment by nlogozzo** [comment]
Does `Path.Combine` throw if a character is invalid or does it just ignore it?

**Comment by UrtsiSantsi** [comment]
Hmm:

> ArgumentException
> 
> .NET Framework and .NET Core versions older than 2.1: One of the strings in the array contains one or more of the invalid characters defined in [GetInvalidPathChars()](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidpathchars?view=net-7.0#system-io-path-getinvalidpathchars).

I also checked the code [(https://github.com/dotnet/runtime/blob/b715349c6bed12a4645a9971e1f75a0845469c6f/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L633)] and it really doesn't check for invalid characters anymore.

**Comment by nlogozzo** [comment]
Ah so then really I don't see any benefit...thanks tho :)

**Comment by UrtsiSantsi** [comment]
For me the first argument - "It checks whether the first path already has a separator at the end so it will not duplicate the separators" - is more important, but it is up to you :)

**Comment by nlogozzo** [comment]
I've never run into any issues within `File` methods where the paths have double separators....and plus the string definition is instant whereas `Path.Combine` needs to call through a method so I think it's best to just leave it the way it is.

**Pull request closed without merging**
